# Generated by Django 4.2.17 on 2025-01-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_updated_on',
            new_name='updated_on',
        ),
    ]
